config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'recipes#index'
  resources :recipes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :find_recipe, only: [:show, :edit, :update, :destroy]

  def index
    @recipes = Recipe.all
  end

  def show

  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    if @recipe.save
      redirect_to recipes_path
    else
      render :new
    end
  end

  def edit

  end

  def update
    if @recipe.update(recipe_params)
      redirect_to recipes_path
    else
      render :edit
    end
  end

  def destroy
    @recipe.destroy
    redirect_to recipes_path
  end

end

private

def find_recipe
  @recipe = Recipe.find(params[:id])
end

def recipe_params
  params.require(:recipe).permit(:name, :ingredient, :create_at)
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/recipes/_form.html.erb
<%= form_for(@recipe) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :ingredient %>
  <%= f.text_field :ingredient %>
  <%= f.submit %>
<% end %>

app/views/recipes/create.html.erb
<h1>Recipes#create</h1>
<p>Find me in app/views/recipes/create.html.erb</p>

app/views/recipes/destroy.html.erb
<h1>Recipes#destroy</h1>
<p>Find me in app/views/recipes/destroy.html.erb</p>

app/views/recipes/edit.html.erb
<h1>Edit your recipe</h1>

<%= render 'form' %>
<%= link_to 'back', recipes_path %>

app/views/recipes/index.html.erb
<h1>Recipes:</h1>
<br>
<% @recipes.each do |recipe| %>
  <h2><%= recipe.name %></h2>
  <p><%= link_to 'More details', recipe_path(recipe) %></p>
  <p><%= link_to 'Edit recipe', edit_recipe_path(recipe) %></p>
  <p><%= link_to 'Delete recipe', recipe_path(recipe),
          method: :delete,
          data: { confirm: 'Are you sure?' } %></p>
  <br>
<% end %>
<p><%= link_to 'Add a new recipe', new_recipe_path %></p>

app/views/recipes/new.html.erb
<h1>Add a new recipe:</h1>

<%= render 'form' %>
<%= link_to 'back', recipes_path %>

app/views/recipes/show.html.erb
<h1>Recipe:</h1>
<br>
<h2>Name: <%= @recipe.name %></h2>
<p>Ingredient: <%= @recipe.ingredient %></p>
<p>Creation date: <%= @recipe.created_at %></p>
<p><%= link_to 'Edit recipe', edit_recipe_path %></p>
<p><%= link_to 'Delete recipe', recipe_path,
        method: :delete,
        data: { confirm: 'Are you sure?' } %></p>
<br>
<%= link_to 'back', recipes_path %>

app/views/recipes/update.html.erb
<h1>Recipes#update</h1>
<p>Find me in app/views/recipes/update.html.erb</p>